@startuml
'https://plantuml.com/class-diagram
Solution43 *- Input
Solution43 *- WebBuilder

class Solution43 {
main()
}

class Input {
-String siteName
-String author
-String js
=String css
-String path;
}
class WebBuilder {
-makeFile()
+makeSite()
}

@enduml