@startuml
'https://plantuml.com/class-diagram



Solution46 *-- FrequencyCalculator

class FrequencyCalculator {
+Map<String, Integer> readFile()
+void computeFrequency()
+Map<String, Integer> sortMap()
+void printGraph
}

class Solution46 {
main()
}

@enduml