@startuml
'https://plantuml.com/class-diagram
class ListApp {
    +List<String> sortList()
    +void printList()
    +List<String> readInput()
}

class Solution41 {
    main()
}

Solution41 o-> ListApp


@enduml