@startuml
'https://plantuml.com/class-diagram

Solution44 *-- Reader


class Solution44 {
main()
}

class Reader {
-String input
-void printResult()
+String askInput()
+void setInput()
+String getInput()
+JsonArray readFile()
}

@enduml